# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mission Categories',
            },
        ),
        migrations.CreateModel(
            name='MissionsObjectif',
            fields=[
                ('mepspage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS.mepspage')),
            ],
            options={
                'verbose_name_plural': 'Page',
                'ordering': ('-post_published_on',),
            },
            bases=('MEPS.mepspage',),
        ),
        migrations.CreateModel(
            name='MissionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=500, unique=True)),
                ('category', models.ForeignKey(default='Non spécifié', on_delete=django.db.models.deletion.SET_DEFAULT, to='Missions_Objectifs.missioncategory')),
            ],
        ),
    ]
