# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PUBLICATIONS', '0001_initial'),
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.post')),
            ],
            options={
                'verbose_name_plural': 'Le Cabinet',
            },
            bases=('MEPS_ADMIN.post',),
        ),
        migrations.CreateModel(
            name='CabinetDecretArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Le Cabinet',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='DecretList',
            fields=[
                ('number', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sentence', models.TextField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='CabinetDecretChapter',
            fields=[
                ('cabinetsidebar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabinet.cabinetsidebar')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            bases=('cabinet.cabinetsidebar',),
        ),
        migrations.CreateModel(
            name='DecretCabinet',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.post')),
                ('fait_a', models.CharField(max_length=50)),
                ('fait_le', models.DateField()),
                ('post_category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decrets', to='PUBLICATIONS.publicationcategory', verbose_name='Category')),
            ],
            options={
                'ordering': ('-post_published_on',),
                'abstract': False,
            },
            bases=('MEPS_ADMIN.post',),
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sentence', models.TextField(max_length=500, unique=True)),
                ('article', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.article')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.chapter'),
        ),
    ]
