# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('direction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.direction')),
                ('direction_generale', models.CharField(blank=True, default='EMPLOI', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DGE',
            },
            bases=('MEPS_ADMIN.direction',),
        ),
        migrations.CreateModel(
            name='ProtectionSociale',
            fields=[
                ('direction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.direction')),
                ('direction_generale', models.CharField(blank=True, default='PROTECTION SOCIALE', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DGPS',
            },
            bases=('MEPS_ADMIN.direction',),
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('direction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.direction')),
                ('direction_generale', models.CharField(blank=True, default='TRAVAIL', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DGT',
            },
            bases=('MEPS_ADMIN.direction',),
        ),
    ]
