# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsServicesRattachés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/directions/cards/')),
                ('full_form_name', models.CharField(max_length=1000, verbose_name='Name')),
                ('short_form_name', models.CharField(blank=True, default='', help_text='Ex: ECIS (école ivoirienne pour les sourds)', max_length=15, unique=True, verbose_name='Sigle')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bp', models.CharField(blank=True, max_length=300, null=True, verbose_name='BP')),
                ('tel', models.CharField(blank=True, max_length=300, verbose_name='Tel')),
                ('phone', models.CharField(blank=True, max_length=300, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=300, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=150)),
                ('post_published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('post_created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('post_modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('display_first', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Page',
            },
        ),
    ]
