# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dssm',
            fields=[
                ('directiondetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.directiondetail')),
            ],
            options={
                'verbose_name_plural': 'Page',
            },
            bases=('MEPS_ADMIN.directiondetail',),
        ),
        migrations.CreateModel(
            name='DssmSousDirection',
            fields=[
                ('sousdirection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.sousdirection')),
                ('dssm_Sous_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.sousdirection',),
        ),
        migrations.CreateModel(
            name='DssmProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.project')),
                ('dssm_Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.project',),
        ),
        migrations.CreateModel(
            name='DssmObjectif',
            fields=[
                ('objectif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.objectif')),
                ('dssm_Objectif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.objectif',),
        ),
        migrations.CreateModel(
            name='DssmMission',
            fields=[
                ('mission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.mission')),
                ('dssm_Mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.mission',),
        ),
        migrations.CreateModel(
            name='DssmContactTel',
            fields=[
                ('contacttel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.contacttel')),
                ('dssm_ContactTel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.contacttel',),
        ),
        migrations.CreateModel(
            name='DssmContactHoraire',
            fields=[
                ('contacthoraire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.contacthoraire')),
                ('dssm_ContactHoraire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.contacthoraire',),
        ),
        migrations.CreateModel(
            name='DssmContactEmail',
            fields=[
                ('contactemail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.contactemail')),
                ('dssm_ContactEmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.contactemail',),
        ),
        migrations.CreateModel(
            name='DssmContactAddress',
            fields=[
                ('contactaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.contactaddress')),
                ('dssm_ContactAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.contactaddress',),
        ),
        migrations.CreateModel(
            name='DssmContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.contact')),
                ('dssm_Contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dssm.dssm')),
            ],
            bases=('MEPS_ADMIN.contact',),
        ),
    ]
