# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionCustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_form_name', models.CharField(max_length=100, unique=True)),
                ('short_form_name', models.CharField(max_length=10)),
                ('address', models.CharField(default='Plateau - Abidjan', max_length=200)),
                ('tel', models.CharField(blank=True, default='(+225) ', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('horaire', models.CharField(default='Lund- Vend: 07h30 à 16h30', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Une Direction Générale',
                'verbose_name_plural': 'Liste des Directions - Générales',
                'ordering': ['status', 'short_form_name'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ',
                'ordering': ['status', '-published_on'],
            },
        ),
        migrations.CreateModel(
            name='NosContactsCustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_form_name', models.CharField(max_length=100, unique=True)),
                ('short_form_name', models.CharField(max_length=10)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100)),
                ('address', models.CharField(default='Plateau - Abidjan', max_length=200)),
                ('tel', models.CharField(blank=True, default='(+225) ', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('horaire', models.CharField(default='Lund- Vend: 07h30 à 16h30', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Une Direction Générale',
                'verbose_name_plural': 'Liste des Directions - Générales',
                'ordering': ['status', 'short_form_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactsCABINET',
            fields=[
                ('noscontactscustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.noscontactscustommodel')),
            ],
            options={
                'verbose_name': ' Service & Direction rattaché au CABINET',
                'verbose_name_plural': 'Directions & Services du Cabinet',
            },
            bases=('NOUS_JOINDRE.noscontactscustommodel',),
        ),
        migrations.CreateModel(
            name='ContactsDGE',
            fields=[
                ('noscontactscustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.noscontactscustommodel')),
            ],
            options={
                'verbose_name': 'Contact de la DGE',
                'verbose_name_plural': 'Directions de la DGE',
            },
            bases=('NOUS_JOINDRE.noscontactscustommodel',),
        ),
        migrations.CreateModel(
            name='ContactsDGPS',
            fields=[
                ('noscontactscustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.noscontactscustommodel')),
            ],
            options={
                'verbose_name': 'Contact de la DGPS',
                'verbose_name_plural': 'Directions de la DGPS',
            },
            bases=('NOUS_JOINDRE.noscontactscustommodel',),
        ),
        migrations.CreateModel(
            name='ContactsDGT',
            fields=[
                ('noscontactscustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.noscontactscustommodel')),
            ],
            options={
                'verbose_name': 'Contact de la DGT',
                'verbose_name_plural': 'Directions de la DGT',
            },
            bases=('NOUS_JOINDRE.noscontactscustommodel',),
        ),
        migrations.CreateModel(
            name='DGT_directions_contacts',
            fields=[
                ('directioncustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.directioncustommodel')),
                ('direction_generale', models.ForeignKey(default='DGT', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='DGT_directions', to='NOUS_JOINDRE.contactsdgt')),
            ],
            bases=('NOUS_JOINDRE.directioncustommodel',),
        ),
        migrations.CreateModel(
            name='DGPS_directions_contacts',
            fields=[
                ('directioncustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.directioncustommodel')),
                ('direction_generale', models.ForeignKey(default='DGPS', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='DGPS_directions', to='NOUS_JOINDRE.contactsdgps')),
            ],
            bases=('NOUS_JOINDRE.directioncustommodel',),
        ),
        migrations.CreateModel(
            name='DGE_directions_contacts',
            fields=[
                ('directioncustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.directioncustommodel')),
                ('direction_generale', models.ForeignKey(default='DGE', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='DGE_directions', to='NOUS_JOINDRE.contactsdge')),
            ],
            bases=('NOUS_JOINDRE.directioncustommodel',),
        ),
        migrations.CreateModel(
            name='CABINET_directions_contacts',
            fields=[
                ('directioncustommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NOUS_JOINDRE.directioncustommodel')),
                ('direction_generale', models.ForeignKey(default='CABINET', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CABINET_directions', to='NOUS_JOINDRE.contactscabinet')),
            ],
            bases=('NOUS_JOINDRE.directioncustommodel',),
        ),
    ]
