# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('Lieu_de_naissance', models.CharField(max_length=200)),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('parti_politique', models.CharField(max_length=50)),
                ('diplome_de', models.CharField(max_length=200, verbose_name='Diplômé de')),
                ('Profession', models.CharField(max_length=200)),
                ('published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Biographie',
                'ordering': ('-published_on',),
            },
        ),
        migrations.CreateModel(
            name='custumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=250)),
                ('published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
        migrations.CreateModel(
            name='LeMinistre',
            fields=[
                ('biographie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.biographie')),
                ('photo', models.ImageField(null=True, upload_to='Media/images/ministre/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=250, unique_for_date='published_on', verbose_name='Slug')),
                ('biographie', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='biographie')),
                ('declaration', models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='declaration')),
                ('mot_du_ministre', models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='mot du ministre')),
            ],
            options={
                'verbose_name_plural': 'Le Ministre',
                'ordering': ('-published_on',),
            },
            bases=('ministre.biographie',),
        ),
        migrations.CreateModel(
            name='ParcoursProfessionnel',
            fields=[
                ('custummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.custummodel')),
                ('ministre_parcours_professionnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ministre_ParcoursProfessionnel', to='ministre.leministre', verbose_name='Le Ministre')),
            ],
            bases=('ministre.custummodel',),
        ),
        migrations.CreateModel(
            name='ParcoursPolitique',
            fields=[
                ('custummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.custummodel')),
                ('ministre_parcours_politique', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ministre_ParcoursPolitique', to='ministre.leministre', verbose_name='Le Ministre')),
            ],
            bases=('ministre.custummodel',),
        ),
        migrations.CreateModel(
            name='InfoPersonnelle',
            fields=[
                ('custummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.custummodel')),
                ('ministre_Infos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ministre_Infos', to='ministre.leministre', verbose_name='Le Ministre')),
            ],
            bases=('ministre.custummodel',),
        ),
        migrations.CreateModel(
            name='ExpérienceAdministrative',
            fields=[
                ('custummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.custummodel')),
                ('ministre_Experience', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ministre_Experience', to='ministre.leministre', verbose_name='Le Ministre')),
            ],
            bases=('ministre.custummodel',),
        ),
        migrations.CreateModel(
            name='Distinction',
            fields=[
                ('custummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ministre.custummodel')),
                ('ministre_distinction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ministre_distinction', to='ministre.leministre', verbose_name='Le Ministre')),
            ],
            bases=('ministre.custummodel',),
        ),
    ]
