# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PUBLICATIONS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Saisir une rubrique du menu MEPS', max_length=50)),
                ('link', models.SlugField()),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'CTA Button',
                'ordering': ('-activated',),
            },
        ),
        migrations.CreateModel(
            name='DirectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/directions/')),
                ('title', models.CharField(max_length=50)),
                ('sigle', models.CharField(help_text="Saisir le sigle d'une direction du menu Direction Générale", max_length=50)),
                ('parent', models.CharField(blank=True, choices=[('MEPS', 'meps'), ('DIRECTIONS_GENERALES', 'directions')], max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MinistersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/Ministres/')),
                ('name', models.CharField(max_length=100)),
                ('civilite', models.CharField(blank=True, choices=[('1', 'Mr'), ('2', 'Mme')], max_length=3)),
                ('content', models.TextField(max_length=500)),
                ('in_function', models.CharField(choices=[('Ancien ministre', 'Ancien'), ('Actuel Ministre', 'Actuel')], max_length=20)),
                ('start_month', models.CharField(choices=[('Janv', 'Janv'), ('Fév', 'Fév'), ('Mar', 'Mar'), ('Avr', 'Avr'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juil', 'Juil'), ('Août', 'Août'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Déc', 'Déc')], max_length=20)),
                ('start_year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=15)),
                ('end_month', models.CharField(blank=True, choices=[('Janv', 'Janv'), ('Fév', 'Fév'), ('Mar', 'Mar'), ('Avr', 'Avr'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juil', 'Juil'), ('Août', 'Août'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Déc', 'Déc')], max_length=15)),
                ('end_year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ("Aujourd'hui", "Aujourd'hui")], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('wikipedia', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Historique',
                'ordering': ('in_function', '-start_month', '-start_year'),
            },
        ),
        migrations.CreateModel(
            name='MinistrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Ministres/')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Le Ministre',
            },
        ),
        migrations.CreateModel(
            name='LeMinistere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('post_created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('post_modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('image', models.ImageField(null=True, upload_to='images/ministere/', verbose_name='Feature Image')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='post_published_on', verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('place', models.CharField(default='Abidjan', max_length=250, verbose_name='Lieu')),
                ('comment_status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Comment status')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Comments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meps_ministere', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, default='uncategorized', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='PUBLICATIONS.publicationcategory')),
            ],
            options={
                'verbose_name_plural': 'À Propos Du Meps',
                'ordering': ('-post_published_on',),
            },
        ),
        migrations.AddIndex(
            model_name='leministere',
            index=models.Index(fields=['-post_published_on'], name='ministere_l_post_pu_0c6d54_idx'),
        ),
    ]
