# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('pdftype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.pdftype')),
            ],
            options={
                'verbose_name_plural': 'Catégorie',
            },
            bases=('MEPS_ADMIN.pdftype',),
        ),
        migrations.CreateModel(
            name='DocumentSousCategory',
            fields=[
                ('pdftype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.pdftype')),
                ('category', models.ForeignKey(default='inconnu', on_delete=django.db.models.deletion.CASCADE, related_name='document_category', to='DOCUMENTS.documentcategory')),
            ],
            options={
                'verbose_name': 'Sous-catégory',
                'verbose_name_plural': 'Sous-catégories',
            },
            bases=('MEPS_ADMIN.pdftype',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('pdfdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.pdfdocument')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(default='Inconnu', on_delete=django.db.models.deletion.CASCADE, related_name='documents_categories', to='DOCUMENTS.documentcategory')),
                ('sous_category', models.ForeignKey(default='Autres', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='documents_subcategories', to='DOCUMENTS.documentsouscategory')),
            ],
            bases=('MEPS_ADMIN.pdfdocument',),
        ),
    ]
