# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostActualite',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.post')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['post_title'],
            },
            bases=('MEPS_ADMIN.post',),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.comment')),
            ],
            bases=('MEPS_ADMIN.comment',),
        ),
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': '_Catégories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationSousCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUBLICATIONS.publicationcategory')),
            ],
            options={
                'verbose_name': 'Sous-Catégorie',
                'verbose_name_plural': '_Sous-Catégories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostCommunique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pdf', models.FileField(upload_to='communique/%Y/%m/%d/')),
                ('post_title', models.CharField(max_length=1000, unique_for_date='post_created_on')),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('post_published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('post_created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('post_slug', models.SlugField(blank=True, max_length=200)),
                ('com_category', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='PUBLICATIONS.publicationcategory', verbose_name='Category')),
                ('com_sous_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUBLICATIONS.publicationsouscategory', verbose_name='Sous-Category')),
            ],
            options={
                'verbose_name': 'Communiqué',
                'verbose_name_plural': 'Communiqués',
                'ordering': ['-post_published_on'],
            },
        ),
        migrations.CreateModel(
            name='PostAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/posts/%Y/%m/%d/Album/%m/%d/')),
                ('photos', models.FileField(default=None, null=True, upload_to='images/posts/%Y/%m/%d/Album/%m/%d/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_album', to='PUBLICATIONS.postactualite', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.AddField(
            model_name='postactualite',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUBLICATIONS.publicationcategory'),
        ),
    ]
