# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/produits/', verbose_name='Feature Image')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique_for_date='published_on', verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('place', models.CharField(default='Abidjan', max_length=250, verbose_name='Lieu')),
                ('published_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('comment_status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Comment status')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Name')),
                ('category_slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('slider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='MEPS_ADMIN.slider')),
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PRODUITS.product')),
            ],
            options={
                'verbose_name': 'Régime',
                'verbose_name_plural': 'Régimes',
                'ordering': ('-published_on',),
            },
            bases=('PRODUITS.product', 'MEPS_ADMIN.slider'),
        ),
        migrations.CreateModel(
            name='ProductRsti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUITS.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Régime RSTI',
            },
        ),
        migrations.CreateModel(
            name='ProductComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUITS.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Régime COMPLEMENTAIRE',
            },
        ),
        migrations.CreateModel(
            name='ProductCmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUITS.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Régime CMU',
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category_name'], name='PRODUITS_pr_categor_51bd64_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='PRODUITS.productcategory'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='PRODUITS_pr_id_2c3de7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='PRODUITS_pr_title_8d592f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_on'], name='PRODUITS_pr_created_820c80_idx'),
        ),
    ]
