# Generated by Django 4.1.6 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PUBLICATIONS', '0001_initial'),
        ('MEPS_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MepsPage',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MEPS_ADMIN.post')),
                ('category', models.ForeignKey(blank=True, default='uncategorized', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='PUBLICATIONS.publicationcategory')),
            ],
            options={
                'ordering': ('-post_published_on',),
                'abstract': False,
            },
            bases=('MEPS_ADMIN.post',),
        ),
    ]
